#flyway.user=databaseUser
#flyway.password=databasePassword
#flyway.schemas=schemaName
#ou bien config equivalente dans pom.xml

flyway.user=postgres
#flyway.user=sa
flyway.password=root
#flyway.password=
flyway.schemas=purchase_db
#flyway.url=jdbc:h2:~/mydb1
flyway.url=jdbc:postgresql://localhost:5432/purchase_db
#flyway.locations=filesystem:db/migration/purchase
flyway.locations=filesystem:src/main/resources/db/migration/purchase
