#flyway.user=databaseUser
#flyway.password=databasePassword
#flyway.schemas=schemaName
#ou bien config equivalente dans pom.xml

flyway.user=root
#flyway.user=sa
flyway.password=root
#flyway.password=
flyway.schemas=mydbbank1
#flyway.url=jdbc:h2:~/mydb1
flyway.url=jdbc:mysql://localhost:3306/mydbbank1?createDatabaseIfNotExist=true
flyway.locations=filesystem:db/migration
