

# FATAL,ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
logging.level.tp.appliSpring=DEBUG

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:~/mydbbank
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=