

# FATAL,ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
logging.level.tp.appliSpring=DEBUG


#maria_db = version simplifiee de mySql (compatible)
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mydbbank?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=create
# via =create , les tables sont re-crees a chaque redemarrage en fonction de la structure java (@column, , ...)