spring.application.name=mySpringBoot
server.servlet.context-path=/mySpringBoot
server.port=8080

#niveaux de logs: ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
#logging.level.tp.mySpringBoot=ERROR
logging.level.tp.mySpringBoot=DEBUG

spring.profiles.active=dev2

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:~/mydbbank 
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ddl-auto pour demander une creation automatique des tables
# au démarrage de l'application ou d'un test unitaire
# valeurs possibles : none, create et update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=none