spring.application.name=mySpringBoot
server.servlet.context-path=/mySpringBoot
server.port=8080

#niveaux de logs: ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
#logging.level.tp.mySpringBoot=ERROR
logging.level.tp.mySpringBoot=DEBUG

#spring.profiles.default=dev1
spring.profiles.default=dev2

#NB: true est la valeur par defaut de spring.data.jpa.repositories.enabled
# et ca demande a spring-data de générer automatiquement les implementations
# des interfaces héritant de JpaRepository
spring.data.jpa.repositories.enabled=true
