server.port=8080

spring.application.name=appliSpring

#url par defaut : http://localhost:8080/index.html
server.servlet.context-path=/appliSpring
#url : http://localhost:8080/appliSpring/index.html

#spring.profiles.default est moins prioritaire que spring.profiles.active
spring.profiles.default=dev,reInit