
#ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
logging.level.tp.appliSpring=TRACE

#parametres de connexions a serveur mariaDB (mysql open source) avec access root/root autorise
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/bankDB?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=create