
#ERROR,WARN,INFO,DEBUG,TRACE
logging.level.root=INFO
logging.level.tp.appliSpring=TRACE

#parametres de connexions a serveur mariaDB (mysql open source) avec access root/root autorise
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/bankDB?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

springdoc.swagger-ui.path=/doc-swagger.html

#en mode flyway et sans ddl-auto:
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
# nb: soit spring.flyway.enabled=true avec maven dependency spring-boot-starter-flyway
# soit appel direct/explicite de mvn clean flyway:migrate

#en mode ddl-auto=create et sans flyway:
#spring.jpa.hibernate.ddl-auto=create
#spring.flyway.enabled=false

#options temporaires pour generer des exemples de create-table a partir du mode ddl-auto=create
#pring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/script/create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=src/main/script/drop.sql