spring.flyway.enabled=false
#flyway must be launch via maven (by default and with profile "purchase")

#main DataBase for some products,customers,orders:
spring.datasource.xa-properties.url=jdbc:mariadb://localhost:3306/product_customer_order_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.xa-properties.user=root
spring.datasource.xa-properties.password=root
spring.datasource.unique-resource-name=product_customer_order
spring.datasource.xa-data-source-class-name=org.mariadb.jdbc.MariaDbDataSource
spring.datasource.pool-size=5

#secondary DataBase for purchase:
#version mysql/mariadb:
#spring.purchasedb.datasource.xa-properties.url=jdbc:mariadb://localhost:3306/purchase_db?createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.purchasedb.datasource.xa-properties.user=root
#spring.purchasedb.datasource.xa-properties.password=root
#spring.purchasedb.datasource.unique-resource-name=purchase
#spring.purchasedb.datasource.xa-data-source-class-name=org.mariadb.jdbc.MariaDbDataSource
#spring.purchasedb.datasource.pool-size=5

#version postgresql:
spring.purchasedb.datasource.xa-properties.url=jdbc:postgresql://localhost:5432/purchase_db
spring.purchasedb.datasource.xa-properties.user=postgres
spring.purchasedb.datasource.xa-properties.password=root
spring.purchasedb.datasource.unique-resource-name=purchase
spring.purchasedb.datasource.xa-data-source-class-name=org.postgresql.xa.PGXADataSource
spring.purchasedb.datasource.pool-size=5
#Attention postgresql en mode jta/xa necessite ce parametrage dans postgresql.conf (dans PostgreSQL\14\data ou ailleurs)
# max_prepared_transactions = 64 (zero default value disables the feature)